name: CI/CD Pipeline for SimpleTimeService

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for building Docker image and pushing to Docker Hub
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          # Specify the directory where the Dockerfile is located (app directory)
          docker build -t ananyadasgupta/simpletimeservice:latest ./app
          docker push ananyadasgupta/simpletimeservice:latest

  # Job for running Terraform commands (init, plan, apply)
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -reconfigure

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan

  apply:
    name: Terraform Apply (Requires Manual Approval)
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment:
      name: terraform-apply
        

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Move tfplan to terraform directory
        run: |
          mv tfplan terraform/  # Move downloaded tfplan to terraform directory

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply $(pwd)/tfplan