name: CI/CD Pipeline for SimpleTimeService

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for building Docker image and pushing to Docker Hub
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          # Specify the directory where the Dockerfile is located (app directory)
          docker build -t ananyadasgupta/simpletimeservice:latest ./app
          docker push ananyadasgupta/simpletimeservice:latest

  # Job for running Terraform commands (init, plan, apply)
  terraform_deployment:
    runs-on: ubuntu-latest
    environment:
      name: terraform-apply
    needs: build_and_push_docker_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1

      - name: Terraform Init
        run: |
          # Specify the directory where Terraform configuration files are located (terraform directory)
          cd ./terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd ./terraform
          terraform plan

      # # Manual approval for sensitive changes
      # - name: Wait for manual approval
      #   uses: peter-evans/wait-for-approval@v2
      #   with:
      #     environment: terraform-apply   # The environment name you created in GitHub Actions Environments
      #   id: approval

      - name: Terraform Apply (Manual Approval)
        # if: steps.approval.outputs.approved == 'true'
        run: |
          cd ./terraform
          terraform apply
